#########
# PROJECT
#########

# Replace the values here with your project` information.
project:
  # The name of the organisation or entity that owns this project
  organisation: "Roger Federer Foundation"
  # A live web address for the organisation
  url: "https://www.rogerfedererfoundation.org/"
  # The default contact email address
  email: "support@electricbook.works"
  # The name of the project of books in this folder.
  name: "Natural Playgrounds Toolkit"
  # A one-liner about this project. Useful for Open Graph metadata.
  description: "The Natural Playgrounds Toolkit provides the skills required to build a playground for young children out of natural resources."
  # The logo of the organisation, saved web-ready in /assets
  logo: "publisher-logo.jpg"
  # An image in /assets that stands for the project
  image: "cover.jpg"
  # Credit line, by default in the footer, overidden in locales.yml
  credit: "Built with the [Electric Book](http://electricbook.works)"
  # Primary language code for this project as a whole
  language: "en"
  # App bundle ID unique across all app stores
  app-id: com.example.myapp
  # Version. You must change this with each app update
  version: "1.0.0"


########
# TITLES
########

## Metadata follows [Dublin Core](https://en.wikipedia.org/wiki/Dublin_Core#DCMI_Metadata_Terms)
## Custom fields added to standard DC terms: subtitle, publisher URL
## When listing files, exlude file extensions, and surround them in quotes
## especially if they contain only numbers.

works:
  - directory: "book"
    title: "Natural Playgrounds Toolkit"
    subtitle: ""
    creator: "Talita van der Walt for Penreach" # E.g. the author
    contributor: "" # E.g. other contributors
    subject: "Non-Fiction" # E.g. BISAC terms (https://bisg.org/page/BISACEdition) or BIC (http://editeur.dyndns.org/bic_categories)
    description: "A toolkit for building your own natural playground." # E.g. the blurb
    publisher: "Roger Federer Foundation" # E.g. the publisher, imprint or brand name
    publisher-url: ""
    date: "2015-12-31" # YYYY-MM-DD e.g. publication date
    modified: "2016-06-09" # YYYY-MM-DD e.g. date of last revision
    type: "Education" # e.g. Novel, Poetry, Memoir
    identifier: "" # e.g. ISBN or UUID
    source: "" # e.g. parent ISBN or ISTC
    language: "en" # use ISO 639-1, 639-2, or 639-3 codes (in that order of preference)
    relation: "" # e.g. other edition ISBN
    coverage: "" # e.g. geographic place or chronological time span
    rights: "All rights reserved. No part of this book may be reproduced or transmitted in any form or by any electronic or mechanical means, including photocopying and recording, or any other information storage or retrieval system, without written permission from the publisher." # e.g. a copyright statement
    image: "cover.jpg"
    products: # Metadata for each product for this title (only use values that override parent metadata)
      print-pdf: 
        date: "2016-05-07" # YYYY-MM-DD e.g. publication or creation date
        format: "Print" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files:
          - "0-1-titlepage"
          - "0-2-copyright"
          - "0-3-contents"
          - "0-4-introduction"
          - "01"
          - "02"
          - "03"
          - "04"
          - "05"
          - "06-00"
          - "06-01"
          - "06-02"
          - "06-03"
          - "06-04"
          - "06-05"
          - "06-06"
          - "06-07"
          - "06-08"
          - "06-09"
          - "06-10"
          - "06-11"
          - "06-12"
          - "07"
          - "50-01-glossary"
          - "50-02-references"
        toc: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
          - label: "Introduction"
            file: "0-4-introduction"
            class: "toc-frontmatter"
          - label: "Section 1: Understand"
            file: "01"
            children:
              - label: "The importance of play"
                file: "01"
              - label: "What children need to develop"
                file: "01"
                id: "what-children-need-to-develop"
              - label: "Learning through play"
                file: "01"
                id: "learning-through-play"
              - label: "Age-appropriate play"
                file: "01"
                id: "age-appropriate-play"
              - label: "Outdoor free play"
                file: "01"
                id: "outdoor-free-play"
              - label: "Playground safety"
                file: "01"
                id: "playground-safety"
              - label: "How to design your natural playground"
                file: "01"
                id: "how-to-design-your-natural-playground"
          - label: "Section 2: Engage"
            file: "02"
            children: 
              - label: "Involving the community"
                file: "02"
              - label: "How to handle community participation"
                file: "02"
                id: "how-to-handle-community-participation"
              - label: "Facilitating community meetings"
                file: "02"
                id: "facilitating-community-meetings"
          - label: "Section 3: Assess"
            file: "03"
            children:
              - label: "What is a needs assessment?"
                file: "03"
              - label: "How to do a needs assessment"
                file: "03"
                id: "how-to-do-a-needs-assessment"
          - label: "Section 4: Act"
            file: "04"
            children:
              - label: "What is a playground action plan?"
                file: "04"
              - label: "How to write a playground action plan"
                file: "04"
                id: "how-to-write-a-playground-action-plan"
          - label: "Section 5: Monitor and Evaluate"
            file: "05"
            children:
              - label: "What is monitoring and evaluation?"
                file: "05"
              - label: "How to approach monitoring and evaluation"
                file: "05"
                id: "how-to-approach-monitoring-and-evaluation"
          - label: "Toolbox"
            file: "06-00"
            children:
              - label: "Tools at a glance"
                file: "06-00"
              - label: "Tool 1: Partner Finder"
                file: "06-01"
              - label: "Tool 2: Playground Map"
                file: "06-02"
              - label: "Tool 3: Playground Dreams"
                file: "06-03"
              - label: "Tool 4: Resource Inventory"
                file: "06-04"
              - label: "Tool 5: Issue Finder"
                file: "06-05"
              - label: "Tool 6: Risk–Benefit Assessment"
                file: "06-06"
              - label: "Tool 7: Formulating Objectives"
                file: "06-07"
              - label: "Tool 8: Activity Plan"
                file: "06-08"
              - label: "Tool 9: Monitoring Summary"
                file: "06-09"
              - label: "Tool 10: Monitoring Safety"
                file: "06-10"
              - label: "Tool 11: Monitoring Maintenance"
                file: "06-11"
              - label: "Tool 12: Evaluate Results"
                file: "06-12"
          - label: "Facilitator's Guide"
            file: "07"
            children:
              - label: "Notes for facilitators"
                file: "07"
              - label: "Using advocacy"
                file: "07"
                id: "using-advocacy"
              - label: "Using participatory workshops"
                file: "07"
                id: "using-participatory-workshops"
              - label: "Using coaching"
                file: "07"
                id: "using-coaching"
              - label: "Using group study"
                file: "07"
                id: "using-group-study"
              - label: "Using guided self-study"
                file: "07"
                id: "using-guided-self-study"
          - label: "Glossary"
            file: "50-01-glossary"
            class: "toc-endmatter"
          - label: "References"
            file: "50-02-references"
            class: "toc-endmatter"
      web:
        date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital online" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files:
          # - "index"
          - "0-1-titlepage"
          - "0-2-copyright"
          - "0-3-contents"
          - "0-4-introduction"
          - "01"
          - "02"
          - "03"
          - "04"
          - "05"
          - "06-00"
          - "06-01"
          - "06-02"
          - "06-03"
          - "06-04"
          - "06-05"
          - "06-06"
          - "06-07"
          - "06-08"
          - "06-09"
          - "06-10"
          - "06-11"
          - "06-12"
          - "07"
          - "50-01-glossary"
          - "50-02-references"
        nav: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
          - label: "Contents"
            file: "0-3-contents"
            class: "toc-frontmatter"
          - label: "Introduction"
            file: "0-4-introduction"
            class: "toc-frontmatter"
          - label: "Section 1: Understand"
            file: "01"
            children:
              - label: "The importance of play"
                file: "01"
              - label: "What children need to develop"
                file: "01"
                id: "what-children-need-to-develop"
              - label: "Learning through play"
                file: "01"
                id: "learning-through-play"
              - label: "Age-appropriate play"
                file: "01"
                id: "age-appropriate-play"
              - label: "Outdoor free play"
                file: "01"
                id: "outdoor-free-play"
              - label: "Playground safety"
                file: "01"
                id: "playground-safety"
              - label: "How to design your natural playground"
                file: "01"
                id: "how-to-design-your-natural-playground"
          - label: "Section 2: Engage"
            file: "02"
            children: 
              - label: "Involving the community"
                file: "02"
              - label: "How to handle community participation"
                file: "02"
                id: "how-to-handle-community-participation"
              - label: "Facilitating community meetings"
                file: "02"
                id: "facilitating-community-meetings"
          - label: "Section 3: Assess"
            file: "03"
            children:
              - label: "What is a needs assessment?"
                file: "03"
              - label: "How to do a needs assessment"
                file: "03"
                id: "how-to-do-a-needs-assessment"
          - label: "Section 4: Act"
            file: "04"
            children:
              - label: "What is a playground action plan?"
                file: "04"
              - label: "How to write a playground action plan"
                file: "04"
                id: "how-to-write-a-playground-action-plan"
          - label: "Section 5: Monitor and Evaluate"
            file: "05"
            children:
              - label: "What is monitoring and evaluation?"
                file: "05"
              - label: "How to approach monitoring and evaluation"
                file: "05"
                id: "how-to-approach-monitoring-and-evaluation"
          - label: "Toolbox"
            file: "06-00"
            children:
              - label: "Tools at a glance"
                file: "06-00"
              - label: "Tool 1: Partner Finder"
                file: "06-01"
              - label: "Tool 2: Playground Map"
                file: "06-02"
              - label: "Tool 3: Playground Dreams"
                file: "06-03"
              - label: "Tool 4: Resource Inventory"
                file: "06-04"
              - label: "Tool 5: Issue Finder"
                file: "06-05"
              - label: "Tool 6: Risk–Benefit Assessment"
                file: "06-06"
              - label: "Tool 7: Formulating Objectives"
                file: "06-07"
              - label: "Tool 8: Activity Plan"
                file: "06-08"
              - label: "Tool 9: Monitoring Summary"
                file: "06-09"
              - label: "Tool 10: Monitoring Safety"
                file: "06-10"
              - label: "Tool 11: Monitoring Maintenance"
                file: "06-11"
              - label: "Tool 12: Evaluate Results"
                file: "06-12"
          - label: "Facilitator's Guide"
            file: "07"
            children:
              - label: "Notes for facilitators"
                file: "07"
              - label: "Using advocacy"
                file: "07"
                id: "using-advocacy"
              - label: "Using participatory workshops"
                file: "07"
                id: "using-participatory-workshops"
              - label: "Using coaching"
                file: "07"
                id: "using-coaching"
              - label: "Using group study"
                file: "07"
                id: "using-group-study"
              - label: "Using guided self-study"
                file: "07"
                id: "using-guided-self-study"
          - label: "Glossary"
            file: "50-01-glossary"
            class: "toc-endmatter"
          - label: "References"
            file: "50-02-references"
            class: "toc-endmatter"
        start-page: "0-3-contents" # At which file should users start reading?
        contents-page: "0-3-contents" # Your contents-page file, if you have one.
      epub:
        date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital download" # e.g. Paperback, Digital download, Digital online
        identifier: "9780000000000" # e.g. ISBN or UUID
        image: "cover.jpg"
        start-page: "0-3-contents"
        contents-page: "0-3-contents"
        files: # add a value to any file to set any of the guide types listed in http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.6
          - "0-0-cover": "cover"
          - "0-1-titlepage": "title-page"
          - "0-2-copyright": "copyright-page"
          - "0-3-contents": "toc"
          - "0-4-introduction": "text"
          - "01"
          - "02"
          - "03"
          - "04"
          - "05"
          - "06-00"
          - "06-01"
          - "06-02"
          - "06-03"
          - "06-04"
          - "06-05"
          - "06-06"
          - "06-07"
          - "06-08"
          - "06-09"
          - "06-10"
          - "06-11"
          - "06-12"
          - "07"
          - "50-01-glossary"
          - "50-02-references"
        toc: # For each menu item, include at least label and file (epub requires file). Optionally add id (for deep linking) and children.
          - label: "Cover"
            file: "0-0-cover"
          - label: "Title page"
            file: "0-1-titlepage"
          - label: "Copyright"
            file: "0-2-copyright"
          - label: "Contents"
            file: "0-3-contents"
          - label: "Chapter One"
            file: "01"
            id: "1-hello-world"
          - label: "Chapter Two"
            file: "02"
            id: "2-goodbye-world"
            children:
              - label: "Subsection"
                file: "02"
                id: "example-id"
      screen-pdf:
        date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital download" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files:
          - "0-1-titlepage"
          - "0-2-copyright"
          - "0-3-contents"
          - "0-4-introduction"
          - "01"
          - "02"
          - "03"
          - "04"
          - "05"
          - "06-00"
          - "06-01"
          - "06-02"
          - "06-03"
          - "06-04"
          - "06-05"
          - "06-06"
          - "06-07"
          - "06-08"
          - "06-09"
          - "06-10"
          - "06-11"
          - "06-12"
          - "07"
          - "50-01-glossary"
          - "50-02-references"
      app:
        format: "Digital download" # e.g. Paperback, Digital download, Digital online
