# Set site.output == "app"
output: "app"
# Set site.image-set == "images/app"
image-set: "images/app"
# Turn off documentation
collections:
  docs:
    output: false
  app:
    output: true
# Remove baseurl
baseurl: ""
exclude:
# Build tools
- run-linux.sh
- run-mac.command
- run-windows.bat
- Gemfile
- Gemfile.lock
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- eslint.json
- gulpfile.js
- package.json
- package-lock.json
- CNAME
# Things we don't need for an app
- assets/profiles
- /*/package.opf
- /*/toc.ncx
- /*/images/print-pdf
- /*/images/screen-pdf
- /*/images/web
- /*/images/epub
- /*/styles/print-pdf*
- /*/styles/screen-pdf*
- /*/styles/web*
- /*/styles/epub*
# Exclude all of the non-bundled JS files
- assets/js/accordion.js
- assets/js/android-copy-videos.js
- assets/js/android-open-pdf.js
- assets/js/annotation.js
- assets/js/definitions.js
- assets/js/elasticlunr-setup.js
- assets/js/elasticlunr.min.js
- assets/js/footnote-popups.js
- assets/js/footnotes.js
- assets/js/form-storage-checkboxes.js
- assets/js/form-storage-textareas.js
- assets/js/heading-titles.js
- assets/js/list-to-checklist.js
- assets/js/locales.js
- assets/js/mark-parents.js
- assets/js/mark.min.js
- assets/js/mathjax
- assets/js/mcqs.js
- assets/js/nav.js
- assets/js/notifications.js
- assets/js/page-reference.js
- assets/js/polyfills.js
- assets/js/redact.js
- assets/js/render-mathjax.js
- assets/js/render-search-index.js
- assets/js/rotate.js
- assets/js/search-engine.js
- assets/js/search-index.js
- assets/js/search-results.js
- assets/js/search-store.js
- assets/js/search-terms.js
- assets/js/select-list.js
- assets/js/shift-elements.js
- assets/js/show-hide.js
- assets/js/slides.js
- assets/js/svg-inject.min.js
- assets/js/svg-management.js
- assets/js/table-to-form.js
- assets/js/tables.js
- assets/js/videos.js